# Generated by Django 3.0.3 on 2020-05-27 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hart', '0002_auto_20200527_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hartal',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 9, 40, 28, 265196, tzinfo=utc)),
        ),
    ]
